import { useEffect, useMemo, useRef, useState } from 'react';
import type { AgentDefinition, AgentFlag, AppConfig } from '@argus/shared';
import { Play, Check, GitBranch, ChevronDown, Folder, X } from 'lucide-react';
import { isPrimaryModifier } from '../../utils/platform.js';
import { AgentGlyph } from '../ui/AgentGlyph.js';
import {
  Sheet,
  Field,
  TextInput,
  Button,
  Kbd,
  Checkbox,
  Toggle,
  ErrorState,
  LoadingState,
  AlertSheet,
} from '../../components/primitives/index.js';
import { api } from '../../services/api.js';

interface CreateSheetProps {
  config: AppConfig | null;
  initialFolderPath?: string | null;
  onClose: () => void;
  onCreate: (folderPath: string, name: string | undefined, agentType: string, flags: string[], worktreeBranch?: string, worktreeBase?: string) => Promise<void>;
  onSaveFlag?: (agentId: string, flag: AgentFlag) => Promise<void>;
}

const RECENT_FOLDERS_KEY = 'argus.recent-folders';

interface RecentEntry { path: string; lastOpened: number; }

function readRecentFolders(): RecentEntry[] {
  try {
    const stored = localStorage.getItem(RECENT_FOLDERS_KEY);
    return stored ? (JSON.parse(stored) as RecentEntry[]) : [];
  } catch { return []; }
}

function removeFromRecentFolders(path: string): RecentEntry[] {
  const next = readRecentFolders().filter((e) => e.path !== path);
  try { localStorage.setItem(RECENT_FOLDERS_KEY, JSON.stringify(next)); } catch { /* non-critical */ }
  return next;
}

function relativeTime(ms: number): string {
  const diff = Date.now() - ms;
  if (diff < 60_000) return 'just now';
  if (diff < 3_600_000) return `${Math.floor(diff / 60_000)}m ago`;
  if (diff < 86_400_000) return `${Math.floor(diff / 3_600_000)}h ago`;
  if (diff < 604_800_000) return `${Math.floor(diff / 86_400_000)}d ago`;
  return `${Math.floor(diff / 604_800_000)}w ago`;
}

const BUILTIN_AGENTS: AgentDefinition[] = [
  { id: 'claude', name: 'Claude Code', command: 'claude', builtin: true },
  { id: 'gemini', name: 'Gemini', command: 'gemini', builtin: true },
  { id: 'codex',  name: 'Codex',  command: 'codex',  builtin: true },
];

export function CreateSheet({
  config,
  initialFolderPath,
  onClose,
  onCreate,
  onSaveFlag,
}: CreateSheetProps) {
  // Recents — read once on mount (dialog is re-mounted each open)
  const initialRecents = useMemo(() => readRecentFolders(), []);
  const [localRecents, setLocalRecents] = useState<RecentEntry[]>(initialRecents);
  const [recentsOpen, setRecentsOpen] = useState(false);
  const [hoveredRecent, setHoveredRecent] = useState<string | null>(null);
  const recentsRef = useRef<HTMLDivElement>(null);
  // Keyboard-driven highlight in the recents dropdown (index into localRecents),
  // distinct from mouse hoveredRecent and the committed folderPath selection.
  const [highlightedRecent, setHighlightedRecent] = useState(-1);
  const highlightedRowRef = useRef<HTMLDivElement>(null);

  const effectiveInitialFolder = initialFolderPath ?? initialRecents[0]?.path ?? '';
  const [folderPath, setFolderPath] = useState(effectiveInitialFolder);
  const [name, setName] = useState('');
  const [agentId, setAgentId] = useState<string>(config?.defaultAgent ?? 'claude');
  const [flagStates, setFlagStates] = useState<Record<string, boolean>>({});
  const [newFlag, setNewFlag] = useState('');
  const [creating, setCreating] = useState(false);
  const [picking, setPicking] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [confirmDiscard, setConfirmDiscard] = useState(false);

  // Worktree state
  const [isGitRepo, setIsGitRepo] = useState<boolean | null>(null);
  const [useWorktree, setUseWorktree] = useState(false);
  const [branchName, setBranchName] = useState('');
  const [worktreeBase, setWorktreeBase] = useState('');
  const [repoBranches, setRepoBranches] = useState<string[]>([]);
  const [branchConfirm, setBranchConfirm] = useState<{ headCommit: string | null } | null>(null);
  const [initializingGit, setInitializingGit] = useState(false);
  const gitCheckTimer = useRef<ReturnType<typeof setTimeout> | null>(null);
  // Ref drives the async-callback "previous auto value" comparison; the state
  // mirror exposes it for the isDirty computation during render.
  const autoGeneratedBranchRef = useRef('');
  const [autoGeneratedBranch, setAutoGeneratedBranch] = useState('');
  // Latest handlers, kept in refs so the global keydown listener binds once.
  const pickFolderRef = useRef<() => void>(() => {});
  const submitRef = useRef<() => void>(() => {});
  // Synchronous re-entrancy guard: a double-click or held ⌘O fires the handler
  // twice before `picking` state updates, stacking two native dialogs.
  const pickingRef = useRef(false);
  // True while a confirm AlertSheet (discard / branch-exists) owns the keyboard,
  // so the global Enter listener doesn't re-fire submit underneath it.
  const suppressSubmitRef = useRef(false);

  const isDirty = folderPath.trim() !== effectiveInitialFolder || name.trim() !== '' || newFlag.trim() !== '' || branchName !== autoGeneratedBranch;
  const handleClose = () => {
    if (isDirty) setConfirmDiscard(true);
    else onClose();
  };

  const agents = config ? [...BUILTIN_AGENTS, ...config.customAgents] : BUILTIN_AGENTS;
  const agentFlags = config?.agentFlags ?? {};
  const currentFlags = agentFlags[agentId] ?? [];

  // Seed flag checkboxes from the selected agent's defaults whenever the agent
  // changes (adjust-during-render — no effect, runs before paint).
  const [seededAgent, setSeededAgent] = useState<string | null>(null);
  if (seededAgent !== agentId) {
    setSeededAgent(agentId);
    const initial: Record<string, boolean> = {};
    for (const f of currentFlags) initial[f.id] = f.enabled;
    setFlagStates(initial);
  }

  // When the folder is cleared, drop git status immediately (render-time adjust,
  // converges because it's guarded on isGitRepo). We deliberately do NOT blank
  // isGitRepo on every keystroke — keeping the last-known value until the
  // debounced check settles avoids the Agent-isolation panel flickering
  // enabled/disabled as the user types within a non-empty path.
  if (!folderPath.trim() && isGitRepo !== null) {
    setIsGitRepo(null);
  }

  // Debounced git-repo detection when folderPath changes.
  useEffect(() => {
    const folder = folderPath.trim();
    if (gitCheckTimer.current) clearTimeout(gitCheckTimer.current);
    if (!folder) return;
    gitCheckTimer.current = setTimeout(async () => {
      try {
        const result = await api.checkWorktree({ repoPath: folder });
        setIsGitRepo(result.isGitRepo);
        if (result.isGitRepo) {
          const sessionName = name.trim() || folder.split('/').pop() || 'session';
          const slug = sessionName.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
          const auto = `argus/${slug}`;
          // Compare against the PREVIOUS auto value before overwriting it, so
          // an untouched field repopulates when the folder/name changes.
          setBranchName((prev) => (prev === autoGeneratedBranchRef.current || prev === '') ? auto : prev);
          autoGeneratedBranchRef.current = auto;
          setAutoGeneratedBranch(auto);
          try {
            const b = await api.listBranchesForRepo(folder);
            setRepoBranches(b.branches);
            setWorktreeBase((prev) => prev || b.currentBranch || 'HEAD');
          } catch {
            /* base picker falls back to HEAD */
          }
        }
      } catch {
        setIsGitRepo(false);
      }
    }, 300);
    return () => { if (gitCheckTimer.current) clearTimeout(gitCheckTimer.current); };
  }, [folderPath]); // eslint-disable-line react-hooks/exhaustive-deps

  // ⌘O folder picker, ⌘↵ submit. Bind once; call the latest handlers via refs.
  useEffect(() => {
    const onKey = (e: KeyboardEvent) => {
      if (isPrimaryModifier(e) && e.key.toLowerCase() === 'o') {
        e.preventDefault();
        pickFolderRef.current();
        return;
      }
      if (e.key === 'Enter') {
        // A confirm AlertSheet (discard / branch-exists) owns Enter while open.
        if (suppressSubmitRef.current) return;
        // ⌘↵ submits anywhere; plain Enter submits only when focus is NOT in an
        // editable field or on a button — editable fields are handled by the
        // native form (name submits, flag input adds a flag) and buttons keep
        // their native activation (e.g. the Recents toggle opens the dropdown).
        const t = document.activeElement as HTMLElement | null;
        const editable = !!t && (t.tagName === 'INPUT' || t.tagName === 'TEXTAREA' || t.isContentEditable);
        const isButton = !!t && t.tagName === 'BUTTON';
        if (isPrimaryModifier(e)) {
          e.preventDefault();
          submitRef.current();
        } else if (!editable && !isButton) {
          e.preventDefault();
          submitRef.current();
        }
      }
    };
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, []);

  // Dismiss recents dropdown on outside click
  useEffect(() => {
    if (!recentsOpen) return;
    const onDown = (e: MouseEvent) => {
      if (recentsRef.current && !recentsRef.current.contains(e.target as Node)) {
        setRecentsOpen(false);
      }
    };
    document.addEventListener('mousedown', onDown);
    return () => document.removeEventListener('mousedown', onDown);
  }, [recentsOpen]);

  // Seed the keyboard highlight when the dropdown opens (on the current folder if
  // it's in the list, else the first row); clear it when it closes. Render-time
  // adjust keyed on the open transition — mirrors the seededAgent pattern above
  // and avoids a cascading-render setState-in-effect.
  const [recentsWasOpen, setRecentsWasOpen] = useState(false);
  if (recentsOpen !== recentsWasOpen) {
    setRecentsWasOpen(recentsOpen);
    if (recentsOpen) {
      const idx = localRecents.findIndex((e) => e.path === folderPath);
      setHighlightedRecent(idx >= 0 ? idx : 0);
    } else {
      setHighlightedRecent(-1);
    }
  }

  // Keep the highlighted row visible within the 220px scroll viewport.
  useEffect(() => {
    if (recentsOpen && highlightedRecent >= 0) {
      highlightedRowRef.current?.scrollIntoView({ block: 'nearest' });
    }
  }, [highlightedRecent, recentsOpen]);

  // Arrow/Enter/Escape navigation for the open recents dropdown. Registered in
  // the CAPTURE phase so it runs before useFocusTrap's document (bubble) Escape
  // handler and the window-level Enter→submit listener — stopPropagation then
  // lets Escape close only the dropdown and Enter select a row without submitting.
  useEffect(() => {
    if (!recentsOpen) return;
    const onKey = (e: KeyboardEvent) => {
      if (e.key === 'ArrowDown') {
        e.preventDefault();
        setHighlightedRecent((h) => Math.min(h + 1, localRecents.length - 1));
      } else if (e.key === 'ArrowUp') {
        e.preventDefault();
        setHighlightedRecent((h) => Math.max(h - 1, 0));
      } else if (e.key === 'Enter') {
        if (highlightedRecent >= 0 && highlightedRecent < localRecents.length) {
          e.preventDefault();
          e.stopPropagation();
          setFolderPath(localRecents[highlightedRecent].path);
          setRecentsOpen(false);
        }
      } else if (e.key === 'Escape') {
        e.preventDefault();
        e.stopPropagation();
        setRecentsOpen(false);
      }
    };
    document.addEventListener('keydown', onKey, true);
    return () => document.removeEventListener('keydown', onKey, true);
  }, [recentsOpen, highlightedRecent, localRecents]);

  const handleRemoveRecent = (path: string) => {
    const next = removeFromRecentFolders(path);
    setLocalRecents(next);
    // Re-clamp the highlight so it never points past the shortened list.
    setHighlightedRecent((h) => Math.min(h, next.length - 1));
  };

  const handlePickFolder = async () => {
    setRecentsOpen(false); // picking a folder dismisses the recents dropdown
    if (pickingRef.current) return; // a dialog is already open
    pickingRef.current = true;
    setPicking(true);
    try {
      const p = await api.pickFolder();
      if (p) setFolderPath(p);
    } catch {
      setError('Folder picker unavailable.');
    } finally {
      pickingRef.current = false;
      setPicking(false);
    }
  };

  const handleSubmit = async (e?: React.FormEvent, skipBranchConfirm = false) => {
    e?.preventDefault();
    if (!folderPath.trim()) {
      setError('Folder is required.');
      return;
    }

    // Capture branch + base before any awaits (state batching guard)
    const branch = (isGitRepo && useWorktree) ? branchName.trim() : '';
    const base = (isGitRepo && useWorktree) ? worktreeBase.trim() : '';

    // Pre-flight: check if branch already exists
    if (branch && !skipBranchConfirm) {
      try {
        const check = await api.checkWorktree({ repoPath: folderPath.trim(), branch });
        if (check.branchExists) {
          setBranchConfirm({ headCommit: check.headCommit ?? null });
          return;
        }
      } catch {
        // proceed anyway on check failure
      }
    }

    setCreating(true);
    setError(null);
    try {
      const selected = currentFlags.filter((f) => flagStates[f.id]).map((f) => f.value);
      await onCreate(folderPath.trim(), name.trim() || undefined, agentId, selected, branch || undefined, base || undefined);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to spawn');
    } finally {
      setCreating(false);
    }
  };

  const handleAddFlag = async () => {
    const v = newFlag.trim();
    if (!v || !onSaveFlag) return;
    const flag: AgentFlag = { id: crypto.randomUUID(), value: v, enabled: false };
    try {
      await onSaveFlag(agentId, flag);
      setFlagStates((prev) => ({ ...prev, [flag.id]: true }));
      setNewFlag('');
    } catch {
      setError('Could not save flag');
    }
  };

  const handleGitInit = async () => {
    const folder = folderPath.trim();
    if (!folder) return;
    setInitializingGit(true);
    try {
      await api.gitInit(folder);
      const r = await api.checkWorktree({ repoPath: folder });
      setIsGitRepo(r.isGitRepo);
    } catch {
      setError('Could not initialize git repository.');
    } finally {
      setInitializingGit(false);
    }
  };

  // Keep keyboard-shortcut refs pointing at the latest closures.
  useEffect(() => {
    pickFolderRef.current = () => void handlePickFolder();
    submitRef.current = () => void handleSubmit();
    suppressSubmitRef.current = confirmDiscard || branchConfirm !== null;
  });

  if (!config) {
    return (
      <Sheet title="New shell" eyebrow="ARGUS · CREATE" onClose={onClose} width={560}>
        <LoadingState label="Loading config" />
      </Sheet>
    );
  }

  return (
    <>
    <Sheet
      title="New shell"
      eyebrow="ARGUS · CREATE"
      subtitle="Spin up an agent. Pick a folder, configure flags, hit Spawn."
      width={560}
      onClose={handleClose}
      dirty={isDirty}
      onConfirmClose={() => setConfirmDiscard(true)}
      footer={
        <>
          <Button variant="ghost" onClick={handleClose}>
            Cancel <span style={{ marginLeft: 6 }}><Kbd>esc</Kbd></span>
          </Button>
          <Button
            variant="primary"
            icon={Play}
            onClick={() => handleSubmit()}
            disabled={creating || !folderPath.trim()}
            loading={creating}
          >
            Spawn shell <span style={{ marginLeft: 6 }}><Kbd>⌘↵</Kbd></span>
          </Button>
        </>
      }
    >
      <form
        onSubmit={handleSubmit}
        style={{ display: 'flex', flexDirection: 'column', gap: 'var(--s-5)' }}
      >
        <Field label="Working folder" required hint="click path or ⌘O to browse">
          <div ref={recentsRef} style={{ position: 'relative' }}>
            {/* Split button: left = native picker, right = recents dropdown */}
            <div style={{
              display: 'flex',
              height: 36,
              background: 'var(--bg-1)',
              border: '1px solid var(--line-2)',
              borderRadius: 'var(--r-2)',
              overflow: 'hidden',
            }}>
              {/* Left: native OS picker — a real button so it's keyboard-focusable
                  (Tab + Enter/Space) and excluded from the global Enter→submit. */}
              <button
                type="button"
                onClick={handlePickFolder}
                style={{
                  all: 'unset',
                  flex: 1,
                  display: 'flex',
                  alignItems: 'center',
                  gap: 'var(--s-2)',
                  padding: '0 var(--s-3)',
                  cursor: 'pointer',
                  borderRight: localRecents.length > 0 ? '1px solid var(--line-2)' : 'none',
                  overflow: 'hidden',
                  minWidth: 0,
                  boxSizing: 'border-box',
                }}
              >
                <Folder size={13} strokeWidth={1.5} color="var(--fg-3)" style={{ flexShrink: 0 }} />
                <span style={{
                  flex: 1,
                  fontFamily: 'var(--font-mono)',
                  fontSize: 'var(--t-sm)',
                  color: picking ? 'var(--fg-2)' : folderPath ? 'var(--fg-0)' : 'var(--fg-3)',
                  overflow: 'hidden',
                  textOverflow: 'ellipsis',
                  whiteSpace: 'nowrap',
                  pointerEvents: 'none',
                }}>
                  {picking ? 'opening…' : folderPath || '~/work/project'}
                </span>
              </button>

              {/* Right: recents toggle — only when history exists */}
              {localRecents.length > 0 && (
                <button
                  type="button"
                  onClick={() => setRecentsOpen((o) => !o)}
                  style={{
                    display: 'flex',
                    alignItems: 'center',
                    gap: 4,
                    padding: '0 10px',
                    flexShrink: 0,
                    background: recentsOpen ? 'var(--accent-bg)' : 'transparent',
                    border: 'none',
                    cursor: 'pointer',
                    color: recentsOpen ? 'var(--accent)' : 'var(--fg-2)',
                    fontSize: 'var(--t-xs)',
                    fontFamily: 'var(--font-sans)',
                    fontWeight: 600,
                    whiteSpace: 'nowrap',
                    transition: 'background 0.12s, color 0.12s',
                  }}
                >
                  Recents
                  <ChevronDown
                    size={11}
                    strokeWidth={2.5}
                    style={{ transition: 'transform 0.15s', transform: recentsOpen ? 'rotate(180deg)' : 'none' }}
                  />
                </button>
              )}
            </div>

            {/* Recents dropdown. onClick preventDefault: this dropdown lives inside
                Field's <label>, so clicking a non-interactive row would forward a
                synthetic click to the label's control (the picker button) and pop the
                OS folder dialog. preventDefault cancels that forwarding; React onClick
                handlers still run, so selecting a recent folder works. */}
            {recentsOpen && localRecents.length > 0 && (
              <div onClick={(e) => e.preventDefault()} style={{
                position: 'absolute',
                top: 'calc(100% + 4px)',
                left: 0,
                right: 0,
                zIndex: 50,
                background: 'var(--bg-2)',
                border: '1px solid var(--line-3)',
                borderRadius: 'var(--r-2)',
                overflow: 'hidden',
                boxShadow: '0 8px 28px rgba(0,0,0,0.45)',
              }}>
                <div style={{
                  padding: '6px 10px 5px',
                  fontSize: 10,
                  fontWeight: 700,
                  letterSpacing: '0.09em',
                  textTransform: 'uppercase' as const,
                  color: 'var(--fg-3)',
                  borderBottom: '1px solid var(--line-2)',
                }}>
                  Recent folders
                </div>
                <div style={{ maxHeight: 220, overflowY: 'auto' as const }}>
                  {localRecents.map((entry, index) => {
                    const isActive = entry.path === folderPath;
                    const isHovered = hoveredRecent === entry.path;
                    const isHighlighted = highlightedRecent === index;
                    const basename = entry.path.split('/').pop() || entry.path;
                    return (
                      <div
                        key={entry.path}
                        ref={isHighlighted ? highlightedRowRef : undefined}
                        onMouseEnter={() => { setHoveredRecent(entry.path); setHighlightedRecent(index); }}
                        onMouseLeave={() => setHoveredRecent(null)}
                        onClick={() => { setFolderPath(entry.path); setRecentsOpen(false); }}
                        style={{
                          display: 'flex',
                          alignItems: 'center',
                          gap: 9,
                          padding: '7px 10px',
                          cursor: 'pointer',
                          borderBottom: '1px solid var(--line-1)',
                          background: isActive ? 'var(--accent-bg)' : (isHovered || isHighlighted) ? 'var(--bg-3)' : 'transparent',
                          transition: 'background 0.08s',
                        }}
                      >
                        <Folder
                          size={12}
                          strokeWidth={1.5}
                          color={isActive ? 'var(--accent)' : 'var(--fg-3)'}
                          style={{ flexShrink: 0 }}
                        />
                        <div style={{ flex: 1, overflow: 'hidden', minWidth: 0 }}>
                          <div style={{
                            fontSize: 'var(--t-xs)',
                            fontWeight: 600,
                            color: isActive ? 'var(--accent-hover)' : 'var(--fg-0)',
                            overflow: 'hidden',
                            textOverflow: 'ellipsis',
                            whiteSpace: 'nowrap',
                          }}>
                            {basename}
                          </div>
                          <div style={{
                            fontFamily: 'var(--font-mono)',
                            fontSize: 10,
                            color: 'var(--fg-3)',
                            overflow: 'hidden',
                            textOverflow: 'ellipsis',
                            whiteSpace: 'nowrap',
                            marginTop: 1,
                          }}>
                            {entry.path}
                          </div>
                        </div>
                        <div style={{ display: 'flex', alignItems: 'center', gap: 6, flexShrink: 0 }}>
                          <span style={{ fontSize: 10, color: isActive ? 'color-mix(in srgb, var(--accent) 60%, transparent)' : 'var(--fg-3)', whiteSpace: 'nowrap' }}>
                            {relativeTime(entry.lastOpened)}
                          </span>
                          {isActive && <Check size={11} strokeWidth={2.5} color="var(--accent)" />}
                          <button
                            type="button"
                            onClick={(e) => { e.stopPropagation(); handleRemoveRecent(entry.path); }}
                            title="Remove from recents"
                            style={{
                              display: 'flex',
                              alignItems: 'center',
                              justifyContent: 'center',
                              width: 18,
                              height: 18,
                              borderRadius: 3,
                              border: 'none',
                              background: 'transparent',
                              cursor: 'pointer',
                              color: 'var(--fg-3)',
                              padding: 0,
                              opacity: isHovered ? 1 : 0,
                              transition: 'opacity 0.1s, color 0.1s, background 0.1s',
                            }}
                            onMouseEnter={(e) => {
                              (e.currentTarget as HTMLButtonElement).style.background = 'rgba(220,80,80,0.15)';
                              (e.currentTarget as HTMLButtonElement).style.color = '#e05d5d';
                            }}
                            onMouseLeave={(e) => {
                              (e.currentTarget as HTMLButtonElement).style.background = 'transparent';
                              (e.currentTarget as HTMLButtonElement).style.color = 'var(--fg-3)';
                            }}
                          >
                            <X size={11} strokeWidth={2.5} />
                          </button>
                        </div>
                      </div>
                    );
                  })}
                </div>
                <div style={{
                  padding: '5px 10px',
                  fontSize: 10,
                  color: 'var(--fg-3)',
                  textAlign: 'center' as const,
                  borderTop: '1px solid var(--line-2)',
                }}>
                  {localRecents.length} of 100 · ordered by last opened
                </div>
              </div>
            )}
          </div>
        </Field>

        <Field label="Shell name" hint="optional · auto from folder otherwise">
          <TextInput
            value={name}
            onChange={setName}
            placeholder="e.g. refactor-event-bus"
            mono
          />
        </Field>

        <div style={{ border: '1px solid var(--line-2)', borderRadius: 'var(--r-2)', overflow: 'hidden' }}>
          <div style={{
            display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 'var(--s-3)',
            padding: '10px 12px',
            background: 'var(--bg-1)',
            borderBottom: (useWorktree && isGitRepo) ? '1px solid var(--line-2)' : 'none',
          }}>
            <div>
              <div style={{ fontSize: 'var(--t-sm)', fontWeight: 500, color: isGitRepo === false ? 'var(--fg-3)' : 'var(--fg-0)' }}>
                Agent isolation
              </div>
              <div style={{ fontSize: 'var(--t-xs)', color: 'var(--fg-2)', marginTop: 2 }}>
                {isGitRepo === false
                  ? 'Requires a git repository'
                  : useWorktree
                    ? 'This session works in its own branch — no conflicts with other agents'
                    : 'Prevent file conflicts when running multiple agents on the same repo'}
              </div>
            </div>
            <Toggle
              checked={useWorktree && isGitRepo === true}
              onChange={(v) => setUseWorktree(v)}
              disabled={isGitRepo !== true}
            />
          </div>
          {useWorktree && isGitRepo === true && (
            <div style={{ padding: '10px 12px', background: 'var(--bg-2)', display: 'flex', flexDirection: 'column', gap: 6 }}>
              <div style={{ fontSize: 'var(--t-xs)', fontWeight: 600, color: 'var(--fg-2)', textTransform: 'uppercase', letterSpacing: '0.06em' }}>
                Branch name
              </div>
              <div style={{ display: 'flex', alignItems: 'center', gap: 'var(--s-2)' }}>
                <GitBranch size={13} strokeWidth={1.6} color="var(--accent)" style={{ flexShrink: 0 }} />
                <TextInput value={branchName} onChange={setBranchName} placeholder="argus/my-feature" mono />
              </div>
              <div style={{ fontSize: 'var(--t-xs)', fontWeight: 600, color: 'var(--fg-2)', textTransform: 'uppercase', letterSpacing: '0.06em', marginTop: 4 }}>
                Base branch
              </div>
              <div style={{ display: 'flex', alignItems: 'center', gap: 'var(--s-2)' }}>
                <GitBranch size={13} strokeWidth={1.6} color="var(--fg-3)" style={{ flexShrink: 0 }} />
                <TextInput value={worktreeBase} onChange={setWorktreeBase} placeholder="HEAD" mono list="create-base-branches" />
                <datalist id="create-base-branches">
                  {repoBranches.map((b) => <option key={b} value={b} />)}
                </datalist>
              </div>
              <div style={{ fontSize: 'var(--t-xs)', color: 'var(--fg-3)' }}>
                New branch starts from here · defaults to the current branch
              </div>
            </div>
          )}
          {isGitRepo === false && (
            <div style={{
              padding: '7px 12px',
              background: 'var(--warn-bg)',
              borderTop: '1px solid color-mix(in srgb, var(--warn) 25%, transparent)',
              display: 'flex',
              alignItems: 'center',
              gap: 'var(--s-3)',
            }}>
              <span style={{ fontSize: 'var(--t-xs)', color: 'var(--warn)', flex: 1 }}>
                ⚠ Not a git repository
              </span>
              <button
                type="button"
                onClick={handleGitInit}
                disabled={initializingGit}
                style={{
                  fontSize: 'var(--t-xs)',
                  color: 'var(--warn)',
                  background: 'transparent',
                  border: '1px solid color-mix(in srgb, var(--warn) 45%, transparent)',
                  borderRadius: 'var(--r-1)',
                  cursor: initializingGit ? 'default' : 'pointer',
                  padding: '2px 8px',
                  fontFamily: 'var(--font-sans)',
                  opacity: initializingGit ? 0.6 : 1,
                  flexShrink: 0,
                }}
              >
                {initializingGit ? 'Initializing…' : 'Initialize'}
              </button>
            </div>
          )}
        </div>

        <Field label="Agent" required>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 'var(--s-2)' }}>
            {agents.map((a) => {
              const isSel = agentId === a.id;
              return (
                <button
                  key={a.id}
                  type="button"
                  onClick={() => setAgentId(a.id)}
                  style={{
                    all: 'unset',
                    cursor: 'pointer',
                    display: 'flex',
                    alignItems: 'center',
                    gap: 'var(--s-2)',
                    padding: 'var(--s-2) var(--s-3)',
                    background: isSel ? 'var(--accent-bg)' : 'var(--bg-1)',
                    border: `1px solid ${isSel ? 'var(--accent-edge)' : 'var(--line-2)'}`,
                    borderRadius: 'var(--r-2)',
                  }}
                >
                  <AgentGlyph agent={a.id} size={22} />
                  <div style={{ flex: 1 }}>
                    <div style={{ fontSize: 'var(--t-sm)', color: 'var(--fg-0)' }}>{a.name}</div>
                    <div className="eyebrow" style={{ marginTop: 2 }}>{a.builtin ? a.id : 'custom'}</div>
                  </div>
                  {isSel && <Check size={14} strokeWidth={2.5} color="var(--accent)" />}
                </button>
              );
            })}
          </div>
        </Field>

        <Field label="Flags" hint={currentFlags.length === 0 ? 'no flags configured' : undefined}>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 4 }}>
            {currentFlags.map((flag) => (
              <label
                key={flag.id}
                style={{
                  display: 'flex',
                  alignItems: 'center',
                  gap: 'var(--s-2)',
                  cursor: 'pointer',
                  padding: '3px 0',
                }}
              >
                <Checkbox
                  checked={!!flagStates[flag.id]}
                  onChange={(v) => setFlagStates((p) => ({ ...p, [flag.id]: v }))}
                  size={14}
                />
                <span style={{ fontFamily: 'var(--font-mono)', fontSize: 'var(--t-sm)', color: 'var(--fg-0)' }}>
                  {flag.value}
                </span>
              </label>
            ))}
            {onSaveFlag && (
              <div style={{ display: 'flex', gap: 'var(--s-2)', marginTop: 'var(--s-2)' }}>
                <div style={{ flex: 1 }}>
                  <TextInput
                    value={newFlag}
                    onChange={setNewFlag}
                    placeholder="--flag-name value"
                    mono
                    onKeyDown={(e) => { if (e.key === 'Enter') { e.preventDefault(); handleAddFlag(); } }}
                  />
                </div>
                <Button variant="outline" size="md" disabled={!newFlag.trim()} onClick={handleAddFlag}>
                  + Add
                </Button>
              </div>
            )}
          </div>
        </Field>

        {error && <ErrorState title="Cannot spawn" detail={error} />}
      </form>
    </Sheet>
    <AlertSheet
      isOpen={confirmDiscard}
      title="Discard new shell?"
      message="You'll lose the folder, name, and flag changes."
      confirmLabel="Discard"
      confirmDestructive
      onConfirm={() => { setConfirmDiscard(false); onClose(); }}
      onCancel={() => setConfirmDiscard(false)}
    />
    <AlertSheet
      isOpen={branchConfirm !== null}
      title={`Branch "${branchName}" already exists`}
      message={branchConfirm?.headCommit ? `Latest commit: ${branchConfirm.headCommit}\n\nThe session will start in this existing branch's worktree.` : 'The session will start in this existing branch\'s worktree.'}
      confirmLabel="Use existing branch"
      onConfirm={() => { setBranchConfirm(null); void handleSubmit(undefined, true); }}
      onCancel={() => setBranchConfirm(null)}
    />
    </>
  );
}
